version: '3.8'

#/etc/hosts
x-hosts:
  &hosts
  extra_hosts:
    - erp.dev.com:${NGINX_IP}

services:
  ### NGINX ################################################
  nginx:
    build: ./nginx
    container_name: nginx
    privileged: true
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
      - ${NGINX_HOST_HTTPS_PORT}:443
    depends_on:
      - php
    volumes:
      # nginx默认配置文件
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      # 项目代码
      - ${WEB_ROOT_PATH}:/var/www/
      # nginx日志
      - ${NGINX_LOG_PATH}:/var/log/nginx/
    networks:
      backend:
        ipv4_address: ${NGINX_IP}

  ### MySQL ################################################
  mysql:
    build:
      context: ./mysql
      args:
        - VERSION=${MYSQL_VERSION}
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${MYSQL_TIMEZONE}
    volumes:
      # mysql默认配置文件
      - ${MYSQL_CONF_PATH}:/etc/mysql/conf.d/docker.cnf
      # 数据文件
      - ${MYSQL_DATA_PATH}:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    privileged: true
    ports:
      - ${MYSQL_PORT}:3306
    networks:
      backend:
        ipv4_address: ${MYSQL_IP}

  ### PHP ################################################
  php:
    build:
      context: ./php
      args:
        - VERSION=${PHP_VERSION}
    container_name: php
    privileged: true
    cap_add:
      - SYS_PTRACE
    ports:
      - 9000:9000
    links:
      - mysql
      - redis
    #/etc/hosts
    <<: *hosts
    volumes:
      # php 配置文件
      - ./php/config/php.ini:/usr/local/etc/php/php.ini
      - ./php/config/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./php/config/php-fpm.d:/usr/local/etc/php-fpm.d
      # 项目代码
      - ${WEB_ROOT_PATH}:/var/www/
      # php-fpm日志
      - ${PHP_LOG_PATH}:/var/log/php/
    networks:
      backend:
        ipv4_address: ${PHP_IP}

  ### Redis ################################################
  redis:
    build:
      context: ./redis
      args:
        - VERSION=${REDIS_VERSION}
    container_name: redis
    command: redis-server /etc/redis/redis.conf
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ${REDIS_DATA_PATH}:/data
      - ${REDIS_CONF_PATH}:/etc/redis/redis.conf
    networks:
      backend:
        ipv4_address: ${REDIS_IP}

  romeo:
    build: ../romeo
    container_name: romeo
    ports:
      - "8080:8080"
    links:
      - "mysql"
    networks:
      backend:
        ipv4_address: ${ROMEO_IP}


networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET}
